### ISSUE TITLE
 archetypeCatalog 'http://repo.auraframework.org/libs-release-local/archetype-catalog.xml' is not supported anymore

### ISSUE THREAD

**Issue by OlegForce** [forcedotcom/aura#100]
Getting errror when trying to run "mvn archetype:generate -DarchetypeCatalog=http://repo.auraframework.org/libs-release-local/archetype-catalog.xml" step 1 of setup guide ----> archetypeCatalog 'http://repo.auraframework.org/libs-release-local/archetype-catalog.xml' is not supported anymore. 

Not a good start :)

**Comment by byao** [comment]
New instructions and archetype has been updated. Please try again and let us know how it goes.

**Comment by OlegForce** [comment]
Thank you.
