### ISSUE TITLE
Lightning Design based Components

### ISSUE THREAD

**Issue by datasert** [forcedotcom/aura#104]
Thank you for this amazing framework.

Any plans to integrate lightning design into aura to create something aura-lightning component set?

**Comment by dianawidjaja** [comment]
Thanks for your interest in the framework. Our SLDS-based components are available in the `lightning` namespace, which are hosted in a private repo. However, you can get to them at our [Lightning Components Dev Guide](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/aura_compref.htm), assuming you have a Developer org or the like. We don't currently have an interactive site but there's an ongoing effort to get that out in the near future. The Dev Guide is your best bet for now.

**Comment by brsanthu** [comment]
thanks @dianawidjaja. Will check out the dev org. But that would be specific to Salesforce. I was hoping to see a component set based on lightning which could be used outside of Salesforce, for ex. in an internal tool.

**Comment by datasert** [comment]
thanks @dianawidjaja. Will check out the dev org. But that would be specific to Salesforce. I was hoping to see a component set based on lightning which could be used outside of Salesforce, for ex. in an internal tool.

**Comment by mleonardsfdc** [comment]
As Diana mentioned, we're working on LDS-styled components in the lightning namespace. The main focus for development is for developers building in Salesforce.

I don't understand your use case fully but a few options might be:
1. Use Lightning Out to use components on a server of your choice. See https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/lightning_out.htm

2. Create your own components and use the markup from https://www.lightningdesignsystem.com/

I hope that helps.

**Comment by datasert** [comment]
Thank you @mleonardsfdc 

I think option# 2 is the way forward for us if we have to use lightning design system.
