### ISSUE TITLE
Https for http://repo.auraframework.org/

### ISSUE THREAD

**Issue by datasert** [forcedotcom/aura#110]
Title says it all

**Comment by mgetzbw** [comment]
This is a different project unrelated to salesforce

**Comment by datasert** [comment]
@mgetzbw thank you for the reply. How is it unrelated to Salesforce? I thought that is the maven repository hosted by Salesforce distribute aura artifacts.

**Comment by mgetzbw** [comment]
@datasert seems you're right I'm not sure they intended to even have that public

**Comment by datasert** [comment]
I think they intended to make that public. They have another repo which is not visible to public.
