### ISSUE TITLE
Assertion Failed!: "text" must either be a public property of exampleTextCmp or a global HTML

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/aura#113]
I followed all the steps in the readme file, but when I open my helloWorld app (using http://localhost:8080/example/helloWorld.app), I have the following error:

`Assertion Failed!: "text" must either be a public property of exampleTextCmp or a global HTML`

<img width="714" alt="auraerror" src="https://user-images.githubusercontent.com/2465122/27396252-c5c0c904-56b2-11e7-8955-885b23d6533c.png">

**Comment by KrisGraySFDC** [comment]
Can you paste what your app code?

**Comment by FabienTaillon** [comment]
Sure, it was the default helloWorld app created by the [step 2](https://github.com/forcedotcom/aura/blob/master/README.md) of the Aura readme file.

**App**
```
<aura:application access="global" useAppcache="false" render="client">
    hello web, from the Aura sample app
    <example:textCmp text="helloworld" />
</aura:application>
```

**Component**
```
<aura:component>
    <aura:attribute name="text" type="String" default="" access="GLOBAL" />
    <p>{!v.text}</p>
</aura:component>
```

If I remove the `text="helloworld"` attribute in the app, it's working fine.
Tried to replace the `textCmp` component with some other like ui:inputText, working fine too.

**Comment by FabienTaillon** [comment]
So I'm still too new to Aura to understand exactly the issue, but it seems that it's what's inside modules/example/text-cmp that is used to render example:textCmp in the app, instead of the component inside components/example/textCmp.

If I delete the folder in modules/example, the helloworld app is working.

**Comment by diervo** [comment]
@FabienTaillon modules is some experimental components we are testing, and when the name matches they are getting picked up instead of the ones defined in the components folder, which is very weird because the namespace should not match.

Looks like a bug, we will take a look.

**Comment by max6cn** [comment]
any updates?
