### ISSUE TITLE
Build break on Windows Due to File.Separator issue in aura-module

### ISSUE THREAD

**Issue by rahul-chaudhary** [forcedotcom/aura#125]
Method getCustomElementName inside  class BundleModuleDefFactory trying to get custom element tag name from path but it fails because on Windows platform.

**Comment by rahul-chaudhary** [comment]
Solution is to make sure that on windows platform the check supplies the correct separator to proceed further. submitting my change. please review.

**Comment by rahul-chaudhary** [comment]
String separator = System.getenv("os").indexOf("Windows")>=0?"/":File.separator;
String[] paths = path.split(separator);        

Here is my change.

**Comment by byao** [comment]
@rahul-chaudhary `File.separator` is supposed to return separator character based on file system. Is that not the case?

**Comment by rahul-chaudhary** [comment]
No it is expecting / as file separator but in case of Windows os the file separator is \ which is why build is breaking.
after adding 
String separator = System.getenv("os").indexOf("Windows")>=0?"/":File.separator;

build goes to next step where it is breaking again. i will raise another issue for that in few minutes.

**Comment by byao** [comment]
Is `System.getenv("os").indexOf("Windows") >= 0 ? "/" : File.separator;` correct ?

if index of "Windows" in "os" exists ie `>= 0`, don't you want "\" for Windows ?

**Comment by rahul-chaudhary** [comment]
The code flow coming from above is very specific to platform dependent separator. It is considering Nix style file separator so when flow reaches to method getCustomElementName inside class BundleModuleDefFactory we are trying to provide separator based on File System which should have been taken care of from the beginning.

Just to give you an example please take a look at public ModuleDef getDefinition(SOME PARAMETER TYPE)

**Comment by rahul-chaudhary** [comment]
This is the error comes when code build on Windows platform. as we can see \ is a Windows file system separator
Exception in thread "main" java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^

**Comment by rahul-chaudhary** [comment]
Looks like the build only works on *Nix platform. On Windows 10 it just breaks down heavily. :-(
Which is kind of a shame
