### ISSUE TITLE
ESLint integration breaking ES6 compatible code

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/aura#127]
[Per the release notes](https://releasenotes.docs.salesforce.com/en-us/winter18/release-notes/rn_lc_validation_on_save.htm) ESLint has been integrated into the aura compiler. Please remove the rules blocking the use of ES6 constructs or allow this to be toggled. Many of us don't need to support IE11 and prefer the expressiveness and clear code that ES6 provides.

If this continues to block saving with ES6 constructs we will have to stop recommending lightning as a development platform.

**Comment by mleonardsfdc** [comment]
There are plans afoot to relax the linting to allow ES6 syntax in a Winter '18 patch. The exact timing of this change isn't clear yet but I'll report back when I get more info.

**Comment by mgetzbw** [comment]
@mleonardsfdc thank you, your response is greatly appreciated. In the mean time would it be possible to get the rules blocking the use of `const` and `let` removed immediately as those are supported for IE11.

My two cents is the ES5 strictness should be controlled by the org opting in to long term IE11 support for lightning.

**Comment by mleonardsfdc** [comment]
@mgetzbw I'm the technical writer on the team and I was just passing on relevant info. 

Your request makes sense so I hope we have positive news to share on that front soon.

**Comment by mleonardsfdc** [comment]
The Winter '18 patch that went out this week made all ES6 syntax valid to the linter.

**Comment by mgetzbw** [comment]
@mleonardsfdc this is now broken by the issues raised in #169
