### ISSUE TITLE
formatTime (and formatDateTime) return time in browser time zone, not Salesforce User time zone

### ISSUE THREAD

**Issue by ZergyPoo** [forcedotcom/aura#129]
Not sure if it's intended or not, but here's my scenario:

1. My user is in PST.
2. I'm located in the midwest, so my browser is in the CST timezone.

And with the following debug:

```
console.log(myDateTime);
console.log($A.get("$Locale.timezone"));
console.log($A.localizationService.formatTime(myDateTime));
```

I get the following output:

2017-09-26T20:30:00.000Z
America/Los_Angeles
3:30:00 PM

The issue is "3:30 PM" is the time in CST, not in PST. This presents difficulties for me since all other parts of the aura/lightning interface display the time in the proper PST, as 1:30 PM.

**Comment by KrisGraySFDC** [comment]
I'll file a bug. Agree, this is just wrong.

**Comment by ZergyPoo** [comment]
I know this was a while ago when I logged it, but was there any update or resolution to this issue?
