### ISSUE TITLE
Lightning Container X-Frame-Options Issue

### ISSUE THREAD

**Issue by pbattisson** [forcedotcom/aura#138]
When using the Lightning container component to display a react application I am receiving an error:

Refused to display '...' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

It seems other are experiencing this as well with the demo application provided by Salesforce (see comments in
https://salesforce.stackexchange.com/questions/186165/lightning-container-index-html-not-in-the-right-folder)

**Comment by pbattisson** [comment]
I have been informed that the repo for the example would be the best place to put this so have moved to https://github.com/developerforce/LightningContainerExamples/issues/7

**Comment by nishprogrammer** [comment]
Is there any fix available for this issue? I am trying to load a VF page in lightning component. It works fine in sandbox but doesn't work in production environment. Both are updated with winter 18 updates.
