### ISSUE TITLE
FileMonitorTest failing in build

### ISSUE THREAD

**Issue by rahul-chaudhary** [forcedotcom/aura#142]
Build is failing due to following
Failed tests: 
  FileMonitorTest.testFileMonitorNotifiesWithRegistryCreationTimeInPast:54 Should not have any errors or warnings expected:<[]> but was:<[[FileMonitorImpl] Unable to monitor directory /home/rahul/Development/Workspace/aura/aura-impl/target/tmp/testFileMonitorNotifiesWithRegistryCreationTimeInPast_jb7ecj7c_5cejyxd81mmf **due to exception: User limit of inotify watches reached]>**

**Comment by lukeis** [comment]
you'll need to increase your local inotify limit:

Here's an article discussing how to do that:
https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

linux by default has a pretty low limit and we often hit that limit and causes this test to be flakey.

**Comment by rahul-chaudhary** [comment]
Thanks, Yes i did that last night and it worked
