### ISSUE TITLE
Auradocs site is down

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/aura#147]
http://documentation.auraframework.org/auradocs is resetting connections.

**Comment by lukeis** [comment]
Thanks, it's back up again now. Updated the automatic job that deploys to notify us of failures in the future 😄 

https://twitter.com/honest_update/status/947885636429721601

**Comment by lukeis** [comment]
@mgetzbw btw, there's also newer docs sites with component reference:

https://developer.salesforce.com/docs/component-library

http://aura-oss-dev.herokuapp.com/en-us/main/aura-oss/intro_framework.htm

**Comment by mgetzbw** [comment]
@lukeis the former doesn't have the lockerAPI viewer, and the latter requires login
