### ISSUE TITLE
Choose archetype:    Your filter doesn't match any archetype 

### ISSUE THREAD

**Issue by lmbugua852** [forcedotcom/aura#150]
I don't know what to input here. I'm trying to install via my mac terminal as per the instructions.

**Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): :**

**Comment by aznthanh23** [comment]
No archetype defined. Using maven-archetype-quickstart (org.apache.maven.archetypes:maven-archetype-quickstart:1.0)
Choose archetype:
   Your filter doesn't match any archetype (hint: enter to return to initial list)
Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): :

I'm on a ubuntu 18.04 and not sure what to input here. Also tried other flags: -DarchetypeCatalog=local, internal, remote but doesn't seem to fit the instructions. Does anyone have any suggestions? thanks.
