### ISSUE TITLE
Proxy object is undefined when Locker Service is active

### ISSUE THREAD

**Issue by micheletriaca** [forcedotcom/aura#156]
Hi,
I've tried to use a javascript Proxy in a Lightning component (v42.0) with Locker Service enabled, but the Proxy object is undefined. Checking the documentation (http://documentation.auraframework.org/lockerApiTest/index.app?aura.mode=DEV), it seems that the Proxy object should be supported.. I've tested it in Chrome 65.0.3325.181 . Without Locker Service everything works as expected.

Thank you

**Comment by micheletriaca** [comment]
Hello, any news about this? Maybe I have to use another channel to ask about Lightning issues?
Thank you

**Comment by jfparadis** [comment]
Hello Michele,

The issue has been fixed in Salesforce Summer '18 coming out in a couple of months.
