### ISSUE TITLE
Non Java Server Side 

### ISSUE THREAD

**Issue by atnmorrison** [forcedotcom/aura#16]
Hi,

I'd like to connect aura components to a non java server side. Which aura files should I be looking at? It seems like I just need to be able to tell aura what endpoint to call and then handle whatever the post parameters are that aura components send to the server? Am i wrong in thinking it's that simple. It would be nice to have examples of this in the docs :) 

Thanks!
Scott

**Comment by wolfch** [comment]
Is there a high level architecture document or diagram that describes the server-side processing?  I was under the impression that Aura was a purely client-side web component architecture like Polymer or ReactJS.  (I thought the Java requirement was a one-off for building the JS libraries)
