### ISSUE TITLE
503 Service Unavailable. Unable to access the aura repository

### ISSUE THREAD

**Issue by vdineshmca** [forcedotcom/aura#163]
Hi,

We are trying to build the framework and build failed with Aura-Util test case. So, changed the pom.xml ( maven surefire plugin to true) then the problem is resolved but facing the below issue while build;

[ERROR] Failed to execute goal on project aura: Could not resolve dependencies f
or project org.auraframework:aura:jar:0.6000-SNAPSHOT: Failed to collect depende
ncies at com.salesforce:omakase:jar:1.2.0: Failed to read artifact descriptor fo
r com.salesforce:omakase:jar:1.2.0: Could not transfer artifact com.salesforce:o
makase:pom:1.2.0 from/to repo.auraframework.org (http://repo.auraframework.org/l
ibs-release): **Failed to transfer file: http://repo.auraframework.org/libs-releas
e/com/salesforce/omakase/1.2.0/omakase-1.2.0.pom. Return code is: 503 , ReasonPh
rase:Service Unavailable. -> [Help 1]**

Unable to access the aura framework repository and returning 503 service unavailable. Could anyone help us to resolve the problem.

Thanks,
Dinesh

**Comment by vdineshmca** [comment]
Hi There,

I have pointed the node.exe path (https://nodejs.org/dist/v4.2.1/win-x64/node.exe) in the pom.xml and the problem got resolved but facing different issue while building the aura-modules;

org.auraframework.throwable.quickfix.InvalidDefinitionException: markup://module
:marker: unsupported os: Windows 8.1

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (c
ompile-modules) on project aura-modules: Command execution failed.: Process exit
ed with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.codehaus.mojo:exec-maven-plugin:1.6.0:exec (compile-modules) on project aura-
modules: Command execution failed.

As per the exception, windows 8.1 we couldn't able to build the aura framework? Then which supporting system we able to build. 

Could anyone faced this type of issue before.

**Comment by byao** [comment]
http://repo.auraframework.org is back up. I don't think windows build environment is fully supported.

**Comment by loganm** [comment]
Seems like repo.auraframework.org is down again

**Comment by loganm** [comment]
And it's back up again today 👍

**Comment by PhilippCl** [comment]
It's down again.
