### ISSUE TITLE
ESLint rules blocking use of async and await

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/aura#169]
Please do not block ES 6 constructs or `async` and `await` in orgs that are not supporting IE11, this is a massive frustration and significantly harms code readability.

**Comment by mgetzbw** [comment]
adding ES6 default parameters to this too as yet another useful tool... that your linting destroys

**Comment by Jamesdinnes** [comment]
Agreed ESLint Rules really need to be updated. Like to know how your issue "significantly harms code readability." however.

**Comment by mgetzbw** [comment]
@Jamesdinnes see the term "Callback hell" `async` and `await` get rid of most of that

**Comment by Jamesdinnes** [comment]
@mgetzbw yeah, I know of it just haven't come across it yet because lightning is meant to be small modular pieces of code.

**Comment by mgetzbw** [comment]
@Jamesdinnes I've done quite a few things that are very promise dependent, not the least of which was some webgl code. Breaking `async` and `await` also makes code using `fetch` for interfacing with external systems more painful

**Comment by kcappieg** [comment]
+1

For a practical use case of async await:
Imagine a component that coordinates a UI with some complex logic. In some cases, data needs to be fetched from the server, in some it does not. The given state of the component alters which data fetch requests are required, etc.

I have such a component with a long promise chain. @Jamesdinnes Not sure what you mean saying lightning is meant to be small modular pieces of code: you'll always need orchestration components for non-trivial apps. My child components are small and modular but they need data from somewhere, and for that I need a data orchestration component.

**Comment by Jamesdinnes** [comment]
@kcappieg I have just never come across an issue where promises are needed over callbacks is all. I prefer callbacks over async for everything, so it's more of a matter of preference.
I don't even know what I meant by my original comment that 😆.
