### ISSUE TITLE
Removing aura-added classes on ui:button

### ISSUE THREAD

**Issue by chexxor** [forcedotcom/aura#18]
The `ui:button` adds unspecified CSS classes. How can I remove them?

My app's source:

```
<ui:button buttonTitle="Login" label="Login" class="btn btn-link" press="{!c.loginToSf}"/>
```

Generated HTML source;

```
<button class="btn btn-link default uiBlock uiButton" title="Login" accesskey="" type="button" data-aura-rendered-by="25:2.a"><span class=" label bBody truncate" dir="ltr" data-aura-rendered-by="28:2.a">Login</span></button>
```

I don't want the `default uiBlock uiButton` classes on that button. How can get rid of them?

It looks like this is directly added in the button's source. Can we add an attribute to `ui:button` which disables the appending these extra classes? Perhaps call that attribute "addThemeClasses" which defaults to "true"?

`ui:button` source:
    <button type="{!v.buttonType}" aura:id="button" class="{!v.class +' '+v.theme+' uiBlock'}" o

**Comment by Shuhani** [comment]
I am trying to apply Bootstrap to ui:button, but it is getting overridden withuiButton class.

Is there any way to achieve this?
