### ISSUE TITLE
Feature Request: prevent access to component methods unless declared in .cmp markup

### ISSUE THREAD

**Issue by rsussland** [forcedotcom/aura#37]
Currently the following code is possible:

in my_componentController.js:

```javascript

 //example 1
  var another_component = cmp.find("my_other_component");
  another_component.helper.private_method(my_variable);
  
 //example 2
  var another_func = another.get("c.action");
  another_func(); 
 ``` 

Which makes component encapsulation difficult. I would like 1) to always fail, and 2) to succeed only if the action is marked as exportable in the .cmp file.

**Comment by dutchchasman** [comment]
Locker Service addresses this encapsulation breakage.
