### ISSUE TITLE
Building from source fails

### ISSUE THREAD

**Issue by rajdeepd** [forcedotcom/aura#38]
After cloning from source. Local compilation from source fails with the error 
Executed the following command where aura was cloned

`$ mvn install`
Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:run (xunit.js) on project aura-impl

**Detailed output**

[INFO] --- maven-antrun-plugin:1.6:run (xunit.js) @ aura-impl ---
[INFO] Executing tasks

main:
     [echo] Executing tests
     [java] Java Result: 225
     [echo] Generating test report in junit format
     [copy] Copying 1 file to /home/ubuntu/work/aura/aura-impl/target/surefire-reports
     [echo] Test report completed: /home/ubuntu/work/aura/aura-impl/target/surefire-reports/TEST-xunit.xml
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Aura Framework ..................................... SUCCESS [  2.086 s]
[INFO] aura-interfaces .................................... SUCCESS [  0.673 s]
[INFO] aura-spring ........................................ SUCCESS [  0.186 s]
[INFO] aura-util .......................................... SUCCESS [  8.153 s]
[INFO] aura ............................................... SUCCESS [  3.192 s]
[INFO] aura-impl-expression ............................... SUCCESS [  1.431 s]
[INFO] aura-impl .......................................... FAILURE [ 32.775 s]
[INFO] aura-tools ......................................... SKIPPED
[INFO] aura-components .................................... SKIPPED
[INFO] aura-resources ..................................... SKIPPED
[INFO] aura-integration-test .............................. SKIPPED
[INFO] aura-jetty ......................................... SKIPPED
[INFO] auradocs-integration-test .......................... SKIPPED
[INFO] archetype for Aura-based "hello, world" ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 48.832 s
[INFO] Finished at: 2015-11-04T11:23:22+05:30
[INFO] Final Memory: 38M/413M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:run (xunit.js) on project aura-impl: An Ant BuildException has occured: There were xUnit.js test failures. Check /home/ubuntu/work/aura/aura-impl/target/surefire-reports/TEST-xunit.xml -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :aura-impl

**Comment by gordosfdc** [comment]
Can you please let us know what platform you are on,including the version
of java and exactly what tests failed (from the xml file). We do a full set
of integration tests on every commit (but only on ubuntu linux), and so I
would guess that this is a problem on a specific platform.

**Comment by daden** [comment]
I'm also getting an error on aura-impl, but a different one. I'm on OSX 10.11.6 (El Capitan). Here's the error: 

[INFO] 
[INFO] --- frontend-maven-plugin:0.0.28:npm (run-xunit) @ aura-impl ---
[INFO] Found proxies: []
[INFO] Running 'npm run --color=false test -- /dependency:./aura-util/src/test/tools/xUnit/dependencies /output:text /strict:true /verbose:false /dev_exclusions/auraFrame/aura-impl/src/test/javascript' in /dev_exclusions/auraFrame/aura-impl/..
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] aura-impl .......................................... FAILURE [ 38.252 s]
[INFO] aura-tools ......................................... SKIPPED
[INFO] aura-components .................................... SKIPPED
[INFO] aura-resources ..................................... SKIPPED
[INFO] aura-integration-test .............................. SKIPPED
[INFO] aura-jetty ......................................... SKIPPED
[INFO] archetype for Aura-based "hello, world" ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 38.540 s
[INFO] Finished at: 2016-09-09T12:42:45-04:00
[INFO] Final Memory: 19M/437M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.28:npm (run-xunit) on project aura-impl: Failed to run task: 'npm run --color=false test -- /dependency:./aura-util/src/test/tools/xUnit/dependencies /output:text /strict:true /verbose:false /dev_exclusions/auraFrame/aura-impl/src/test/javascript' failed. java.io.IOException: Cannot run program "/dev_exclusions/auraFrame/aura-impl/../node/node" (in directory "/dev_exclusions/auraFrame/aura-impl/.."): error=2, No such file or directory -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by wolfch** [comment]
As I mentioned in issue #60 - the reason for this error is that the tests in the `aura-impl` require `node`, `npm` and the `grunt` node module - it will try to use it's own version and not any version of `node` you may already have on your PATH.  

You need to run the following Maven goal before any others:
```
$ mvn pre-clean
```
This will apparently install a version of `node`, `npm` under a directory `${project.basedir}/node` and `grunt` module under a directory `${project.basedir}/node_modules`.  In other words, it will use it's own downloaded version of `node` and `npm` regardless of what you have installed, if any.

I did run `mvn clean` per the instructions, but I suppose this didn't implicitly call `mvn pre-clean`.

I highly recommend updating [aura_oss.pdf](https://github.com/forcedotcom/aura/blob/master/aura_oss.pdf) "Quick Start" / "Build from Source" to mention that you must run `mvn pre-clean` _before_ `mvn install`.

BTW, this worked for me on MacOS 10.11 (El Capitan).

**Comment by jsrawat89** [comment]
@rajdeepd are you able to resolve this error ? I am also getting this error 
-----------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (run-xunit) on project aura-impl: Failed to run task: 'npm run --color=false test 

On windows 10
Java : 1.8

Please help me to resolve this error.
