### ISSUE TITLE
Who is owner of forcedotcom github?

### ISSUE THREAD

**Issue by colleen1** [forcedotcom/aura#40]
Hi,

How can I get access to forcedotcom github?

1. https://github.com/forcedotcom organization
2. https://github.com/orgs/forcedotcom/teams/desksdk team

Thanks,

Colleen Smith
Desk - dev manager
colleen.smith@salesforce.com

**Comment by dutchchasman** [comment]
@colleen1 assume you found an appropriate forcedotcom admin
