### ISSUE TITLE
Aura UI elements are built not using Lightning Design System styles

### ISSUE THREAD

**Issue by nzchicken** [forcedotcom/aura#43]
Not sure whether there is a better place to report this or not. It looks like ui elements have their own style supplied by aura. Should these elements have a default style? If yes, then why are they not Lightning Design System styles?

I'm assuming this repo flows down to Salesforce Production of course. If this is not the case, please let me know where I can raise this as an issue/defect.

**Comment by JasonXM** [comment]
Aura is different from Lightning Component.Now In the latest release you can use lightning design system based component just use lightning:xxx tag . Go through new document and you will not miss it .

**Comment by mleonardsfdc** [comment]
Aura OSS is technically supposed to work for any generic web app and is not tied to Salesforce. The ui namespace predates the Lightning Design System and contains components that are not styled with Salesforce branding.

The lightning namespace, as JasonXM mentions, uses the Lightning Design System so is the way to go for Salesforce apps. This is admittedly confusing but the ui components were designed this way.
