### ISSUE TITLE
Consider using typescript for javascript

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/aura#49]
Given that typescript reduces bugs, has really nice tooling, and produces code that browsers internal JITs can run faster. It would be worthwhile to consider looking at transitioning to typescript.

**Comment by gordosfdc** [comment]
This is a possibility for the future, but cannot be done at the moment.

**Comment by mgetzbw** [comment]
@gordosfdc just curious, any specific reason why? The code base wouldn't break if you transitioned as is. Anything valid for the closure compiler would be valid typescript. This would also make IE 11 continued support easier.
