### ISSUE TITLE
Use of ES6 Default Param Value spec in JS functions

### ISSUE THREAD

**Issue by pchittum** [forcedotcom/aura#50]
I'm attempting to create a helper function where I want to supply some default values (it is to wrap the `e.force:showToast` event, but could be for any reason, really).

ES6's [default parameter value spec](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Default_parameters) is so nice and syntax sugarlicious, I though I would give that a try. 

No luck. 

Here is the function definition: 

```
fireToast : function(msg = 'No Message Specified', 
                     title = 'Wobble Message' , 
                     duration = 5000, key, mode, type = 'info'){...}
```

When I attempt to save this, I get the following error: 

> ERROR: 0Ad240000008RPA: org.auraframework.util.json.JsonStreamReader$JsonStreamParseException: Expected ',' or ')' [64, 30]: '='

Not the end of the world, but would be really nice to have. Thanks!

**Comment by gordosfdc** [comment]
This will hopefully be coming at some point in the future, but we currently don't have a way to allow it as the version of closure compiler that we have doesn't support this.

**Comment by emilyrose** [comment]
Is there something that prevents us from upgrading the version of closure compiler?

**Comment by mgetzbw** [comment]
It looks like they are locked on a Java 6 version for some reason from 2013: v20130411 

Given that there are significant fixes in [later releases](https://github.com/google/closure-compiler/wiki/Releases) this should be a priority now that ES6 browsers will be the default post January 2018.
