### ISSUE TITLE
ECMAScript Map and Set are not accessible in Aura components

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/aura#52]
Description:
======
add the following line to a helper or controller function:

    var foo = new Map(),
        bar = new Set();

Expected result:
======
`foo` and `bar` are defined as the native ECMAScript 6 `Map` and `Set` objects

Actual Result:
======
an error is thrown saying that `Map is not a constructor`

**Comment by dutchchasman** [comment]
Fix for this is already in master as you have discovered and is being cherry picked into 204/patch (the branch that corresponds to Winter'17) and is targeted to deploy on Salesforce around 10/18

For reference this bug is tracked inside Salesforce by W-3280484
