### ISSUE TITLE
Lockerservice breaks Select onchange event

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/aura#53]
using the following component HTML:

```HTML
<fieldset>
    <select onchange="{!c.selectChanged}">
        <option>a</option>
        <option>b</option>
    </select>
</fieldset>
```

and controller:

```javascript
({
    selectChanged:function(component, event, helper){
          var foo = event.srcElement.selectedIndex;
          if (foo === undefined){
              alert("fail");
          }
    }
})
```

Expected result:
=======
Selecting a new value returns a DOM event from the `<select>` element

Actual result:
=======
Selecting a new value returns a DOM event incompatible with the expected event

**Comment by dutchchasman** [comment]
Fixed in master and being cherry-picked to 204/patch (corresponds to patch for Winter'17 Salesforce release expected out on or near 10/18)
