### ISSUE TITLE
Is there a reason for blocking all possible local Storage functions in LockerService?

### ISSUE THREAD

**Issue by vc4u** [forcedotcom/aura#56]
There is a known issue here - https://success.salesforce.com/issues_view?id=a1p3A000000IYE6QAO

Based on this, I'm ins a need to get/set local storage either localStorage or document cookie storage. But, document cookie is implemented as a Read-Only option and localStorage is not available at all.

I was wondering if this is going to happen or not in LockerService when it's rolled out to all?

Is there any workaround available other than disabling LockerService for Lightning Component to work and be able to store local values?

**Comment by dutchchasman** [comment]
We do have plans to implement SecureLocalStorage along with a secuer virtualizaed cookie layer in a future release

**Comment by vc4u** [comment]
Thanks Doug for the info. Is there any estimated timeframe to look out for?

**Comment by dutchchasman** [comment]
We're still trying to figure that out - LS has revealed that there is a significantly larger amount of 3rd party javascript usage than many inside of Salesforce realized and we're adjusting our plans to ficus more on supporting the full spectrum before requiring activation (e.g. we just moved the critical update activation date from 10/18 out to Feb'17). We've also had some issues internally with getting our own code (3rd party library CKEditor actually) to comply with CSP unsafe-inline/unsafe-eval enforcement. We've also increased our staffing investment in the LS team and are continuing to do so. 

As a workaround have you considered using a hidden VF "worker" page in an iframe wrapped by a component that provides your own postMessage() based "proxy" to store in the localstorage of the VF page?

**Comment by vc4u** [comment]
Ohh I didn't realize that the LockerService activation date has been pushed, this is much relief :-)

I've not tried the postMessage() and iframe vf page-based approach, but I'll see if its doable in regards to performance based solution. My only worry was, once past the activation date, we cannot guide any subscriber of the component to deactivate the LockerService, but now it seems we've time. And iframe vf pages have performance drain concerning page load times on mobile devices :)

Thanks again, for your info and your good work on this project!

**Comment by zachelrath** [comment]
@dutchchasman Just curious - closed because Local Storage has been implemented in LockerService? If so... that was fast. YOU GUYS ROCK :)

**Comment by dutchchasman** [comment]
Closed as an issue here because it was a question asking for clarification on "why" and the feature request is being tracked by W-3173101

**Comment by Oblongmana** [comment]
For anyone else coming across this, W-3173101 can be found here: https://success.salesforce.com/issues_view?id=a1p3A000000IYE6QAO
