### ISSUE TITLE
Intl platform Namespace should not be blocked by locker

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/aura#62]
Internationalization is important, preventing the ability to query for localized formatting increases the pain of the devlopement

**Comment by dutchchasman** [comment]
@mgetzbw please elaborate - Locker is simply exposing the public parts of the Aura API that the Aura FW team has signed up to support externally. What is being blocked that you think should not be?

**Comment by mgetzbw** [comment]
@dutchchasman so in this case we needed to be able to find the currency symbol via the currencyisocode, currently Aura exposes no utility to do this but [`intl`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) does. There is [no reason this functionality should not be supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) as it is currently supported on all browsers that aura or salesforce lightning experience support.

**Comment by dutchchasman** [comment]
Perfect - just wanted to make sure we were talking about the same thing - and the fix for this is already in master and being cherry picked into 204/patch (the branch that corresponds to Salesforce Winter'17 patch) and is scheduled for release on or near 10/18.
