### ISSUE TITLE
Locker Service prevents access to options array in a <select> element

### ISSUE THREAD

**Issue by micheletriaca** [forcedotcom/aura#63]
Consider the following lightning component:
### Component: ###
```
<aura:component implements="force:appHostable,flexipage:availableForAllPageTypes,flexipage:availableForRecordHome,force:hasRecordId,forceCommunity:availableForAllPageTypes" access="global" >	        
    <aura:attribute name="selectedValue" type="String" />    
    <select aura:id="theSelect">
        <option value="x">x</option>
        <option value="y">y</option>        
    </select>

    <button onclick="{!c.showSelectedValue}">Show selected value</button>
    <div>{!v.selectedValue}</div>
</aura:component>
```

### Controller: ###
```
({
	showSelectedValue : function(component, event, helper) {
        var el = component.find('theSelect').getElement();
        component.set('v.selectedValue', el.options[el.selectedIndex].value)
	}
})
```

I select a value, then I click on 'show selected value' button. I get the following error:

> Something has gone wrong. Action failed: c$TestSelect$controller$showSelectedValue [Cannot  read property 'undefined' of undefined]
> Failing descriptor: {c$TestSelect$controller$showSelectedValue}.
> Please try again.

It seems that the options array is not exposed by the Locker Service. If I disable Locker Service, everything is working fine

**Comment by Tr4nki** [comment]
You are right, the framework doesn't exposes that property on select input element.

This is a workarround that i use while it isn't available

**COMPONENT**
```
<aura:component>          
    <aura:attribute name="selectedValue" type="String" />    
    <select aura:id="theSelect" onblur="{!c.updateValue}" >
        <option value="x">x</option>
        <option value="y">y</option>        
    </select>

    <div>{!v.selectedValue}</div>
</aura:component>
```

**CONTROLLER**
```
({
       updateValue : function(component, event, helper) {
        var opts=event.currentTarget.getElementsByTagName("option"); //The options of "select" inputElement
        
        var value="";
        opts.forEach(function(opt,index,list){
            value=opt.selected?opt.value:value;
        }); 
        component.set("v.selectedValue",value);
    }
})
```

**Comment by micheletriaca** [comment]
Thank you @Tr4nki, the workaround works in the simple use case of the above component. 
Unfortunately, the problem is that this issue is preventing me to use some third party libraries that rely on that parameter, and I don't want to modify the source code of the library. What I would like to know is:
1. Is it a bug or there is a security reason to blacklist that parameter?
2. If it is a bug, when it will be fixed?
My code (and the code in the libraries) is in strict mode and is CSP compliant, but I want to be sure that at least i can freely manipulate the DOM of the html inside my component.
I fear to develop something that will break when the locker service will be activated

**Comment by Tr4nki** [comment]
Yes, it sould be implemented every time you want use it :(
I've experienced a lot of troubles working with 3rd part libraries wich manipulates the DOM because locker services doesn't expose all methods and properties of DOM interfaces, this is the case of SELECT input element. 
I think here is where LS exposes properties and methods of DOM interfaces
[HTMLSelectElement Declaration](https://github.com/forcedotcom/aura/blob/d08e5e071349374e0778fafca29aab74ef780787/aura-impl/src/main/resources/aura/locker/SecureElement.js#L895)
It seems in the last version, the value property is included, but if you are working with a lower version or in a salesforce enviroment, im pretty sure that unfortunately you (we) can't use it freely.

I think @davejm can tell more about this.

**Comment by dchasman** [comment]
Fix for this is already in master as you have discovered and is being cherry picked into 204/patch (the branch that corresponds to Winter'17) and is targeted to deploy on Salesforce around 10/18

**Comment by dutchchasman** [comment]
Fix for this is already in master as you have discovered and is being cherry picked into 204/patch (the branch that corresponds to Winter'17) and is targeted to deploy on Salesforce around 10/18

For reference this bug is tracked inside Salesforce by W-3187388

**Comment by micheletriaca** [comment]
Thank you very much @dutchchasman
