### ISSUE TITLE
Aura should not force page reload when token expires

### ISSUE THREAD

**Issue by mattgoldspink** [forcedotcom/aura#65]
We use some of our lightning components in a hybrid HTML5 mobile application. Unfortunately we see the app being forced to fully reload itself when the token for Lightning has expired. Since Lightning/Aura does not OWN the page in this context it should not fully refresh the page and instead allow us to hook into some event that lets us know when the token is expired and allow us to take the best action appropriate to re-initialize Lightning.

I took a look and I see the issue is due to:
- An invalid session causes this JS to be sent to client - https://github.com/forcedotcom/aura/blob/c7d0b8f0c9be8947e5dd04b25da8f81e99d20fb1/aura/src/main/java/org/auraframework/throwable/InvalidSessionException.java
- Which in turn through a number of other calls ends up forcing the hardRefresh to be called - https://github.com/forcedotcom/aura/blob/bc9ac1105da8cd9e8ae8d092e18dadaf3f2ebc6c/aura-impl/src/main/resources/aura/AuraClientService.js#L708

Is there anyway we can disable this?

Thanks,
Matt

**Comment by kevinv11n** [comment]
Discussed on support forums with @mattgoldspink  and work item has been added to our backlog.
