### ISSUE TITLE
Docs menu not working

### ISSUE THREAD

**Issue by ceiroa** [forcedotcom/aura#66]
The left menu at http://documentation.auraframework.org/auradocs#reference, which I'm assuming is auto-generated from this repo, does not seem to work. Clicking on any of the options, for example Components does not expand the menu.

**Comment by dianawidjaja** [comment]
Thanks for reporting this issue, @ceiroa . We opened a bug for it and the team is taking a look. Meanwhile, for any component you see at https://github.com/forcedotcom/aura/tree/master/aura-components/src/main/components/ui, you can access its docs directly by going to http://demo.auraframework.org/auradocs/reference.app#reference?descriptor=ui:button&defType=component for example (just update the descriptor value).

**Comment by rahul-chaudhary** [comment]
Yes only working for JavaScript API link. Looks like the child items of tree are not getting populated other than JavaScriptAPI.

**Comment by mleonardsfdc** [comment]
It's working again now.

**Comment by rahul-chaudhary** [comment]
Ok i will test again. Thanks for the heads up.
