### ISSUE TITLE
Lockservice breaks databindings in array properties when members are added to array

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/aura#67]
# Description:

Adding onto the end of an array property results in databindings being broken for the items pushed in. This appears to be because the new items are not wrapped in a secure object wrapper. This manifests when the array is iterated and individual members of the array have properties bound to inputs.
# Workaround:

When adding to the array strip the secure object from all array members before assigning back to the property by using `Object.assign({}, item)`
# Expected Behavior

If the array length has grown, then any items not wrapped in a secure object should be wrapped and data-bindings should work
# Actual Behavior

New items in the array don't databind properly as they are not wrapped in secure objects.
# Affected Releases:
- Summer 16
- Winter 17

**Comment by mgetzbw** [comment]
CC  @genebike

**Comment by trevor-bliss** [comment]
Hi @mgetzbw, apologies for the extremely delayed response. Do you have a sandbox running Spring '17 you can try this out on? There have been a significant amount of fixes since this was reported I wouldn't be surprised if it's fixed now.

**Comment by trevor-bliss** [comment]
Haven't heard back in a month, closing this issue.

**Comment by mgetzbw** [comment]
@trevor-bliss this still occurs and is even enshrined in the official trailheads as a hacky workaround using `JSON.parse(JSON.stringify(lockerobject))`

**Comment by trevor-bliss** [comment]
This should all be fixed in Summer '17.
