### ISSUE TITLE
Getting Started/helloworld issue - not finding http://maven.auraframework.org/libs-release

### ISSUE THREAD

**Issue by dajevu** [forcedotcom/aura#69]
Hello,

I'm attempting to follow the instructions for the getting started guide. I've successfully run the archtype setup, which created the helloworld directory and pom.xml. However, when I try to build the project, I then receive:

Failed to execute goal on project helloWorld: Could not resolve dependencies for project org.myGroup:helloWorld:war:1.0-SNAPSHOT: Failed to collect dependencies at org.auraframework:aura-util:jar:0.5001 -> org.auraframework:aura-spring:jar:0.5001 -> org.springframework:spring-webmvc:jar:4.1.7.RELEASE: Failed to read artifact descriptor for org.springframework:spring-webmvc:jar:4.1.7.RELEASE: Could not transfer artifact org.springframework:spring-webmvc:pom:4.1.7.RELEASE from/to libs-internal (http://maven.auraframework.org/libs-release): maven.auraframework.org: Unknown host maven.auraframework.org -> [Help 1]

It appears as though maven.auraframework.org is no longer accessible? What should I update these lines to instead:

<repositories>
    <repository>
        <id>libs-internal</id>
        <url>http://maven.auraframework.org/libs-release</url>
    </repository>
    
    <repository>
        <id>libs</id>
        <url>http://repo.auraframework.org/libs-release</url>
    </repository>
</repositories>

Thanks!

jeff

**Comment by mleonardsfdc** [comment]
Closing as archetype was recently updated. Please reopen if you see further issues.

http://maven.auraframework.org/libs-release is an internal salesforce repo. Try http://repo.auraframework.org/libs-release if you have ongoing issues.
