### ISSUE TITLE
org.auraframework.http.AuraServlet

### ISSUE THREAD

**Issue by happyventures** [forcedotcom/aura#70]
When launching the app from heroku, it fails to launch with the following message
Error: Could not find or load main class org.auraframework.http.AuraServlet

**Comment by Kozille** [comment]
Aura framework - it is appropriate tool to create a marketplace for example like this one:? Easy-to-use catalog website with subsites working and looking like some sort of profiles with some data, just like you can see here https://zoptamo.com/s-bodybuilding-c-us
