### ISSUE TITLE
Incorrect documentation on server-side controllers

### ISSUE THREAD

**Issue by pozil** [forcedotcom/aura#73]
[Documentation PDF](https://github.com/forcedotcom/aura/blob/master/aura_oss.pdf) indicates at page 169 that Java server-side controllers need to have an `@Controller` annotation but that does not work.

This will cause a runtime failure:
```
2016-11-30 13:27:18,645 ERROR [qtp824900551-19] (ExceptionAdapterImpl.java:138) - Unhandled Exception 'class com.pozil.controllers.MySampleController must implement org.auraframework.ds.servicecomponent.Controller' at com.pozil.controllers.MySampleController
```

Implementing the suggested `org.auraframework.ds.servicecomponent.Controller` interface will lead to another error:
```
2016-11-30 13:21:06,833 ERROR [qtp129371198-22] (ExceptionAdapterImpl.java:138) - Unhandled Exception 'Failed to retreive controller instance for java://com.pozil.controllers.MySampleController'
...
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.pozil.controllers.MySampleController] is defined
```

Looking a the project's test code, this looks like the proper way to declare a server-side controller:
```
import org.auraframework.annotations.Annotations.ServiceComponent;
import org.auraframework.ds.servicecomponent.Controller;

@ServiceComponent
public class MySampleController implements Controller {
...
}
```

Could you please:
1. fix the documentation
2. explain what the `@Controller` annotation does
3. fix the "retreive" typo in the exception message :)

**Comment by mleonardsfdc** [comment]
Thanks for reporting this. The doc is out-of-date and @Component is no longer used. As you suggest, use:
@ServiceComponent
public class MySampleController implements Controller {
...
}

I'll work on the doc update and typo fix. Happy Friday!

**Comment by mleonardsfdc** [comment]
PDF has been updated and error messages typos have been fixed. Thanks for letting us know!

**Comment by hmgibson23** [comment]
This results in the same error about not being able to retrieve the controller.

My markup is as follows:
```
package helloWorld;


import org.auraframework.annotations.Annotations.ServiceComponent;
import org.auraframework.ds.servicecomponent.Controller;
import org.auraframework.system.Annotations.AuraEnabled;
import org.auraframework.system.Annotations.Key;

@ServiceComponent
public class SimpleController implements Controller {
        @AuraEnabled
        public static String serverEcho(@Key("firstName")String firstName) {
                return ("From server: " + firstName);
        }
}

```

**Comment by hmgibson23** [comment]
Any help would be appreciated.
