### ISSUE TITLE
Not able to access DOM elements when locker service is enabled

### ISSUE THREAD

**Issue by rahulbussa** [forcedotcom/aura#78]
Not able to access dom element when locker service is enabled.

Cmp File

    <canvas id="canvas" aura:id="mycanvas" ></canvas>

In Controller File

when accessing both methods are not working 

    document.getElementById('canvas')   //return undefined

    component.find('mycanvas').getContext('2d')  //doesn't returns anything

How to access the DOM element when locker service enabled , I'm facing issue in ChartJS integration when locker service is enabled.

**Comment by trevor-bliss** [comment]
You have access to DOM elements that are created in the same namespace you are trying to access them from. I assume your cmp and controller file are the same bundle, and thus the same namespace. 

Where exactly in your controller are you making those calls? If your making the call in the 'init' event handler it may be before any DOM is rendered. Try moving it to a button click handler to verify.

**Comment by rahulbussa** [comment]
@trevor-bliss I had tried it afterScriptsLoaded in ltng:require and also tried it in afterRender (in Render) calling helper function, I'm getting same result both the cases.

**Comment by trevor-bliss** [comment]
Would you mind sharing the relevant code you're using (rest of the markup and javascript for this specific component), as well as library version numbers? I've seen multiple usages of ChartJS working fine with LockerService enabled. Maybe there's something unique about the specific usage of the library.
