### ISSUE TITLE
Unable to use document.getElementsByClassName() in LockerService

### ISSUE THREAD

**Issue by chirag64** [forcedotcom/aura#86]
We're able to use document.getElementById('id-name') and document.querySelector('#id-name') with an ID name in it, but we're unable to select elements using document.getElementsByClassName('class-name') or document.querySelectorAll('.class-name') since it always returns a blank array.

A popular scenario in our team is to get all elements within an aura iteration and this seems to be the best way to get those elements (there are other use cases as well where we need to get elements using class name).

**Comment by trevor-bliss** [comment]
With LockerService active, you only have access to the DOM created by elements from within your same namespace. document.getElementsByClassName() should still work, but will filter out any elements that were created by other namespaces.

If DOM elements you're trying to query for are from components in your same namespace and you think this isn't behaving as expected please share a simple code sample that demonstrates the issue.

**Comment by chirag64** [comment]
Here's a component that I created:

```
<aura:component >
    <div>
        <lightning:layout>
            <lightning:layoutItem class="list-item">First</lightning:layoutItem>
            <lightning:layoutItem class="list-item">Second</lightning:layoutItem>
            <lightning:layoutItem class="list-item">Third</lightning:layoutItem>
            <lightning:layoutItem class="list-item">Fourth</lightning:layoutItem>
        </lightning:layout>
    </div>
    <div>
        <lightning:button variant="brand" label="Click Me" onclick="{!c.clickedBtn}" />
    </div>
</aura:component>
```

And here's the controller code for it:

```
({
	clickedBtn : function(component, event, helper) {
        console.log('getElementsByClassName: ' + document.getElementsByClassName('list-item').length);
        console.log('getElementsByTagName: ' + document.getElementsByTagName('div').length);
	}
})
```

The output that I get in console is:
```
getElementsByClassName: 0
getElementsByTagName: 2
```

I just realized getElementsByTagName is also working incorrectly (since each `<lightning:layoutItem>` is also a div). Does `<lightning:layout>` create it's own namespace?

**Comment by dutchchasman** [comment]
This is working as designed - yes those **lightning:** components are in the **lightning:** namespace and their internal details are encapsulated on purpose. There is no guarantee that the structure of these components at the DOM level will remain even remotely consistent over time - its not part of their API contract.

**Comment by trevor-bliss** [comment]
@chirag64 I'm closing this issue. Feel free to re-open if you see behavior that doesn't align with what Doug and I describe. For your code, please interact with the lightning namespaced components via their public API (access=GLOBAL attributes and methods) rather than the DOM elements as Doug pointed out.
