### ISSUE TITLE
Allow for the use of ECMAScript 6 classes

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/aura#91]
Right now this fails with `org.auraframework.util.json.JsonStreamReader$JsonStreamParseException: Reserved word used as a literal [2, 15]: 'class': Source`

`class` may be a reserved word but it is valid to declare them in the helper and developers should not be blocked from doing so.

**Comment by datasert** [comment]
Supporting ES6 and ES7 would be awesome. If we can stretch further and add support for Typescript, that would be a great way to develop components.

**Comment by mgetzbw** [comment]
@datasert see #49
