### ISSUE TITLE
I could not create a helloWorld example app due to No catalog defined

### ISSUE THREAD

**Issue by nelsonra** [forcedotcom/aura#93]
Hi 

I can't seem to get the hello world example to work. 

I followed the steps outlined in the readme.md file.

I am seeing "No catalog defined" when I try to create my project, I don't think these are the options I should be seeing:

> $ mvn archetype:generate -DarchetypeCatalog=http://repo.auraframework.org/libs-release-local/archetype-catalog.xml
> [INFO] Scanning for projects...
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building Maven Stub Project (No POM) 1
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] >>> maven-archetype-plugin:3.0.0:generate (default-cli) > generate-sources @ standalone-pom >>>
> [INFO]
> [INFO] <<< maven-archetype-plugin:3.0.0:generate (default-cli) < generate-sources @ standalone-pom <<<
> [INFO]
> [INFO] --- maven-archetype-plugin:3.0.0:generate (default-cli) @ standalone-pom ---
> [INFO] Generating project in Interactive mode
> [INFO] No catalog defined. Using internal catalog
> [INFO] No archetype defined. Using maven-archetype-quickstart (org.apache.maven.archetypes:maven-archetype-quickstart:1.0)
> Choose archetype:
> 1: internal -> org.apache.maven.archetypes:maven-archetype-archetype (An archetype which contains a sample archetype.)
> 2: internal -> org.apache.maven.archetypes:maven-archetype-j2ee-simple (An archetype which contains a simplifed sample J2EE application.)
> 3: internal -> org.apache.maven.archetypes:maven-archetype-plugin (An archetype which contains a sample Maven plugin.)
> 4: internal -> org.apache.maven.archetypes:maven-archetype-plugin-site (An archetype which contains a sample Maven plugin site.
>       This archetype can be layered upon an existing Maven plugin project.)
> 5: internal -> org.apache.maven.archetypes:maven-archetype-portlet (An archetype which contains a sample JSR-268 Portlet.)
> 6: internal -> org.apache.maven.archetypes:maven-archetype-profiles ()
> 7: internal -> org.apache.maven.archetypes:maven-archetype-quickstart (An archetype which contains a sample Maven project.)
> 8: internal -> org.apache.maven.archetypes:maven-archetype-site (An archetype which contains a sample Maven site which demonstrates
>       some of the supported document types like APT, XDoc, and FML and demonstrates how
>       to i18n your site. This archetype can be layered upon an existing Maven project.)
> 9: internal -> org.apache.maven.archetypes:maven-archetype-site-simple (An archetype which contains a sample Maven site.)
> 10: internal -> org.apache.maven.archetypes:maven-archetype-webapp (An archetype which contains a sample Maven Webapp project.)
> Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): 7:

Any help would be appreciated.

Thanks
Nelson

**Comment by nelsonra** [comment]
My configuration:

OS : Mac El Capitan
Maven : 3.3.3
JDK : 1.8

**Comment by nelsonra** [comment]
I still haven't got this to work through the terminal console.  I installed Eclipse and got it to work with the maven plugin. Would still like to be able to do this outside of Eclipse.

**Comment by BillyBadBoy** [comment]
This seems to be a problem with the maven 3 versions of the archetype plugins. When you build it creates a local archetype catalog in `/HOME/.m2/repository`, but when you generate it looks for the local catalog in a different place `/HOME/.m2`.

I just copied the `archetype-catalog.xml` file from  `/HOME/.m2/repository` to  `/HOME/.m2` after building the project. Then the helloWorld app can be generated OK.

[Alternatively, you can edit the `aura-archetype/pom.xml` file and downgrade the versions of both of the archetype plugins from 3.01 to 2.4, then everything works exactly as described in the `readme.md` file]

**Comment by byao** [comment]
The repo README has been updated from new instructions. Please give it try. Thanks

**Comment by mleonardsfdc** [comment]
Closing as archetype was recently updated. Please reopen if you see further issues.
