### ISSUE TITLE
http://maven.auraframework.org/libs-release cannot be reached

### ISSUE THREAD

**Issue by gusChan** [forcedotcom/aura#94]
Hi,

I been trying to build my aura application with Maven but I keep getting errors when downloading aura dependencies.

I tried going to http://maven.auraframework.org/libs-release from the browser and it could not be reached.

**Comment by byao** [comment]
http://maven.auraframework.org/libs-release is an internal salesforce repo. Try http://repo.auraframework.org/libs-release
